import {validateReport,reportDay} from './intelligence.mjs';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})+' IST';
let cache=null,lastFetch=0,request=0;
async function load(force=false){if(!force&&cache&&Date.now()-lastFetch<60000)return cache;const r=await fetch('./data/intelligence.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('AI report collection unavailable');const data=await r.json();try{const status=await fetch('./api/automation-status').then(r=>r.ok?r.json():null);data.automation=status;}catch{}if(data.schemaVersion!==2)throw Error('Unsupported report data');for(const field of ['analyses','digests']){if(!Array.isArray(data[field]))throw Error('Invalid report collection');data[field]=data[field].filter(r=>{try{validateReport(r,r.sources);return true;}catch{return false;}});}cache=data;lastFetch=Date.now();return data;}
const regionFor=state=>['Andhra Pradesh','Telangana','Tamil Nadu'].includes(state.region)?state.region:'India';
function bodyHTML(report,compact=false){return report.sections.slice(0,compact?1:undefined).map(section=>`<section class="analysis-section"><h3>${e(section.title)}</h3>${section.items.length?section.items.map(item=>`<div class="analysis-item"><span class="analysis-kind ${item.kind}">${item.kind==='fact'?'Reported development':item.kind==='inference'?'Interpretation':'Suggested follow-up'}</span><p>${e(item.text)}</p><div class="analysis-citations">${item.citations.map(c=>{const s=report.sources.find(s=>s.id===c.sourceId);return `<a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.publisher)} · ${e(fmt(s.publishedAt))} ↗</a>`;}).filter((v,i,a)=>a.indexOf(v)===i).join('')}</div><details class="quote-details"><summary>Supporting source text</summary>${item.citations.map(c=>`<blockquote>${e(c.quote)}</blockquote>`).join('')}</details></div>`).join(''):'<p class="muted">No sufficiently supported analysis for this section in this collection.</p>'}</section>`).join('');}
function reportHTML(report){return `<div class="report-banner"><span class="pill">AI generated · ${e(report.model)}</span><span class="muted">Generated ${e(fmt(report.generatedAt))}</span></div><div class="report-metrics"><span><strong>${report.inputIssues}</strong> stories analysed</span><span><strong>${report.sourceCount}</strong> source records</span><span><strong>${report.verification.withheldItems}</strong> unsupported items withheld</span></div><p class="muted">Source coverage: ${e(fmt(report.inputFrom))} – ${e(fmt(report.inputTo))}. Analysis uses source headlines and available publisher excerpts.</p>${bodyHTML(report)}<details class="evidence"><summary>Report provenance and limits</summary><p>Source collection: ${e(fmt(report.inputGeneratedAt))}. Citations and numbers were checked against the supplied records, followed by a second AI support check. These checks reduce unsupported output but do not independently verify publisher reporting or guarantee an error-free interpretation.</p><p>Suggested follow-ups are recommendations, not completed actions. Missing follow-up reporting does not establish that an issue remains unresolved.</p></details>`;}
function download(report){const text='# CivicDarpan — '+report.region+'\n'+(report.type==='daily'?'Daily report: '+report.date:'AI analysis')+'\nGenerated: '+fmt(report.generatedAt)+'\nModel: '+report.model+'\n\n'+report.sections.map(s=>'## '+s.title+'\n\n'+s.items.map(i=>'['+i.kind+'] '+i.text+'\n'+i.citations.map(c=>{const x=report.sources.find(s=>s.id===c.sourceId);return '- '+x.publisher+' | '+fmt(x.publishedAt)+' | '+x.url;}).join('\n')).join('\n\n')).join('\n\n');const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='civicdarpan-'+report.region.toLowerCase().replaceAll(' ','-')+'-'+report.type+'-'+report.date+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export async function renderIntelligence({container,state,isCurrent,force=false}){const id=++request,region=regionFor(state),type=state.hub==='Daily Report'?'daily':'analysis';container.innerHTML=`<section class="panel"><div class="eyebrow">${type==='daily'?'DAILY REPORT':'AI ANALYSIS'}</div><h2>${e(region)} · ${type==='daily'?'Daily intelligence report':'AI intelligence briefing'}</h2><p>Loading generated reports…</p></section>`;
 try{const data=await load(force);if(id!==request||!isCurrent())return;const analyses=data.analyses.filter(r=>r.region===region).sort((a,b)=>Date.parse(b.generatedAt)-Date.parse(a.generatedAt)),digests=data.digests.filter(r=>r.region===region).sort((a,b)=>b.date.localeCompare(a.date)||Date.parse(b.generatedAt)-Date.parse(a.generatedAt));
  const automationNote=data.automation?.enabled?'Local automation: AI analysis every 6 hours · daily digest at 7 AM IST · runs while the preview server stays on.':data.schedule?.enabled?'Scheduled AI analysis every 6 hours · daily report at 7 AM IST. Scheduled runs may be delayed.':'Showing saved generated reports. Automatic generation is not active on this host.';
  const scopeNote=state.district?`This is the ${region} briefing; it has not been generated specifically for ${state.district}.`:state.region&&region==='India'?`This is the India-wide briefing. ${state.region} does not yet have a separate generated report.`:'';
  if(type==='analysis'){const report=analyses[0];container.innerHTML=`<section class="panel"><div class="panel-title"><div><div class="eyebrow">AI ANALYSIS</div><h2>${e(region)} · AI intelligence briefing</h2></div><button class="outline" id="refresh-ai">Refresh reports ↻</button></div><p class="muted">${e(automationNote)}</p>${scopeNote?`<p class="notice">${e(scopeNote)}</p>`:''}${report?`<button class="outline" id="download-ai">Download briefing ↓</button>${reportHTML(report)}`:'<p>No generated report is available for this edition yet.</p>'}</section>`;container.querySelector('#refresh-ai').onclick=()=>renderIntelligence({container,state,isCurrent,force:true});if(report)container.querySelector('#download-ai').onclick=()=>download(report);}
  else{const selected=state.aiReportDate||digests[0]?.date||reportDay(Date.now()),digest=digests.find(r=>r.date===selected),timeline=analyses.filter(r=>reportDay(r.generatedAt)===selected);container.innerHTML=`<section class="panel"><div class="panel-title"><div><div class="eyebrow">DAILY REPORT</div><h2>${e(region)} · Daily intelligence report</h2></div><label>Date <input type="date" id="ai-report-date" value="${e(selected)}" max="${reportDay(Date.now())}"></label></div><div class="daily-actions"><button class="outline" id="refresh-ai">Refresh reports ↻</button>${digest?'<button class="outline" id="download-ai">Download daily report ↓</button>':''}</div><p class="muted">${e(automationNote)}</p>${scopeNote?`<p class="notice">${e(scopeNote)}</p>`:''}<h3 class="digest-heading">Daily intelligence digest · ${e(selected)}</h3>${digest?.revision>1?`<p class="muted">Revision ${digest.revision} · incorporates a later generation of this day’s reporting.</p>`:''}${digest?reportHTML(digest):'<p>No generated daily digest for this date. Choose another date; historical reports are not invented.'}<h3 class="digest-heading">Executive summary timeline</h3><p class="muted">Actual saved generations on ${e(selected)} IST. New snapshots appear when report generation runs.</p>${timeline.length?'<div class="report-timeline">'+timeline.map(r=>`<article class="timeline-card"><div class="eyebrow">${e(fmt(r.generatedAt))}</div>${bodyHTML(r,true)}<details><summary>View full analysis</summary>${bodyHTML(r)}</details></article>`).join('')+'</div>':'<p class="muted">No executive snapshots were recorded on this date.</p>'}</section>`;container.querySelector('#ai-report-date').onchange=ev=>{state.aiReportDate=ev.target.value;renderIntelligence({container,state,isCurrent});};container.querySelector('#refresh-ai').onclick=()=>renderIntelligence({container,state,isCurrent,force:true});if(digest)container.querySelector('#download-ai').onclick=()=>download(digest);}
 }catch(error){if(id!==request||!isCurrent())return;container.innerHTML=`<section class="panel"><h2>Generated reports are not available yet</h2><p>The report generation may still be running. Previous source-reading lists are not being labelled as AI analysis.</p><button class="outline" id="retry-ai">Check again</button></section>`;container.querySelector('#retry-ai').onclick=()=>renderIntelligence({container,state,isCurrent,force:true});}
}
