import test from 'node:test';import assert from 'node:assert/strict';
import {evidenceKey,IMPACT_VERSION,impactScore,reportedHeat,componentSupported} from '../impact.mjs';
const s={id:'a',url:'https://example.com/a',title:'Water supply unavailable across the city for two days',excerpt:'Residents faced disruption to normal living because water supply was unavailable city-wide for two days.',language:'en',publishedAt:'2026-09-13T12:00:00Z',provenance:{pageFetched:true,headlineMatched:true,timestampLocator:'NewsArticle.datePublished'}};
function source(){const a={...s};a.impactAssessment={sourceId:a.id,version:IMPACT_VERSION,evidenceKey:evidenceKey(a),verified:true,components:{severity:{level:'material_harm',quote:a.excerpt},service:{level:'essential_unavailable',quote:a.title},reach:{level:'district_or_city',quote:a.title},duration:{level:'one_to_three_days',quote:a.title}}};return a;}
const issue=a=>({id:a.id,title:a.title,sources:[a]});
test('Reported disruption is weighted by impact and can be scored from one supported event',()=>assert.equal(impactScore(source().impactAssessment,source()).value,63));
test('Extra articles and duplicated groups neither dilute nor amplify regional impact',()=>{const a=issue(source()),b=issue({...s,id:'b',title:'An art exhibition opens'});assert.equal(reportedHeat([a,b,...Array(100).fill(a)]).value,63);});
test('Unknown duration is not zero and is not removed from the denominator',()=>{const a=source();a.impactAssessment.components.duration=null;assert.equal(impactScore(a.impactAssessment,a).value,null);});
test('Invented support and changed source text invalidate an assessment',()=>{const a=source();a.impactAssessment.components.reach.quote='One million people were affected';assert.equal(impactScore(a.impactAssessment,a),null);const b=source();b.title='Water supply restored';assert.equal(impactScore(b.impactAssessment,b),null);});
test('Later reporting does not inherit the older disruption score',()=>{const a=source(),later={...s,id:'later',publishedAt:'2026-09-14T06:00:00Z',title:'Water supply resumed according to board'};assert.equal(reportedHeat([{id:'event',sources:[a,later]}]).value,null);});
test('A higher supported impact changes the regional maximum, regardless of source counts',()=>{const a=source();a.id='higher';a.excerpt+=' Residents suffered serious injuries.';a.impactAssessment.sourceId=a.id;a.impactAssessment.evidenceKey=evidenceKey(a);a.impactAssessment.components.severity={level:'serious_harm',quote:'Residents suffered serious injuries.'};assert.equal(reportedHeat([issue(source()),issue(a)]).value,73);});
test('Indefinite is not evidence of elapsed duration and a date is not a duration',()=>{for(const quote of ['Doctors begin indefinite strike','Markets closed on September 14'])assert.equal(componentSupported('duration',{level:'over_week_or_recurrent',quote}),false);});
test('A city mention and disrupted services do not establish city-wide harm or complete outage',()=>{assert.equal(componentSupported('reach',{level:'district_or_city',quote:'Delhi hospital services hit'}),false);assert.equal(componentSupported('severity',{level:'serious_harm',quote:'Delhi hospital services hit'}),false);assert.equal(componentSupported('service',{level:'essential_unavailable',quote:'Delhi hospital services hit'}),false);});
