import {publisherPage,publisherState} from './publisher-page.mjs';
import {readFile,writeFile,rename} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {clean,eligible,dated} from '../core.mjs';import {locateIndia,categoryOf,indiaRelevant} from '../v2.mjs';import {publicSources,isPublicSource} from './public-sources.mjs';
const incremental=process.argv.includes('--incremental');
const root=new URL('../',import.meta.url),geo=JSON.parse(await readFile(new URL('assets/geography.json',root)));
const allowed=new Set(publicSources.flatMap(s=>[...s.hosts,...(s.feedHosts||[])]));
async function page(url,depth=0){const u=new URL(url);if(u.protocol!=='https:'||!allowed.has(u.hostname)||depth>4)throw Error('Unapproved redirect');const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(r.status>=300&&r.status<400)return page(new URL(r.headers.get('location'),u).href,depth+1);if(!r.ok)throw Error('HTTP '+r.status);return r.text();}
export function pibTimestamp(raw){const m=raw.match(/(\d{1,2})\s+([A-Z]{3})\s+(\d{4})\s+(\d{1,2}):(\d{2})\s*(AM|PM)/i);if(!m)return null;const month=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'].indexOf(m[2].toUpperCase())+1,h=(+m[4]%12)+(m[6].toUpperCase()==='PM'?12:0);const iso=`${m[3]}-${String(month).padStart(2,'0')}-${m[1].padStart(2,'0')}T${String(h).padStart(2,'0')}:${m[5]}:00+05:30`;return dated(iso)?iso:null;}
const tag=(text,name)=>clean(text.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+name+'>','i'))?.[1]?.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1')||'');
async function monthListing(url,html){const body=new URLSearchParams();for(const m of html.matchAll(/<input\b[^>]*>/gi)){const a={};for(const x of m[0].matchAll(/([\w:-]+)=["']([^"']*)["']/g))a[x[1]]=x[2];if(a.name&&a.type==='hidden')body.set(a.name,a.value||'');}for(const m of html.matchAll(/<select\b[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/select>/gi)){const v=m[2].match(/<option[^>]*selected[^>]*value="([^"]*)"/)||m[2].match(/<option[^>]*value="([^"]*)"/);if(v)body.set(m[1],v[1]);}body.set('ctl00$ContentPlaceHolder1$ddlday','0');body.set('__EVENTTARGET','ctl00$ContentPlaceHolder1$ddlday');const r=await fetch(url,{method:'POST',body,redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('History HTTP '+r.status);return r.text();}
function meta(html,name){for(const m of html.matchAll(/<meta\b[^>]*>/gi)){const a={};for(const x of m[0].matchAll(/([\w:-]+)\s*=\s*(["'])([\s\S]*?)\2/g))a[x[1].toLowerCase()]=x[3];if((a.property||a.name||'').toLowerCase()===name)return clean(a.content);}return '';}
let prior={articles:[]};try{prior=JSON.parse(await readFile(new URL('data/news.json',root)));}catch{}
const accepted=new Map(prior.articles.filter(s=>isPublicSource(s)&&eligible(s)&&Date.now()-Date.parse(s.publishedAt)<30*86400000).map(s=>[s.id,s]));const queues=[],health=[],held={};const hold=k=>held[k]=(held[k]||0)+1;
for(const rule of publicSources){if(incremental&&!rule.parser){health.push(...(prior.feeds||[]).filter(f=>f.url===rule.url));continue;}try{let html=await page(rule.url);let candidates=[];
 if(rule.region){try{html=await monthListing(rule.url,html);}catch(e){hold(e.message);}const ids=[...new Set([...html.matchAll(/PressRelease(?:Detail|Page|IframePage)\.aspx\?PRID=(\d+)/gi)].map(m=>m[1]))];candidates=ids.slice(0,600).map(id=>({url:`https://www.pib.gov.in/PressReleasePage.aspx?PRID=${id}&lang=1&reg=3`,rule}));}
 else{for(const m of html.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)){const item=m[1],published=tag(item,'pubDate');if(!Number.isFinite(Date.parse(published))||Date.now()-Date.parse(published)>30*86400000)continue;candidates.push({url:tag(item,'link').split('#')[0],rule,title:tag(item,'title'),author:tag(item,'dc:creator')});}}
 if(!rule.region&&!candidates.length)throw Error('Feed returned no usable dated items');queues.push(candidates);health.push({publisher:rule.publisher,url:rule.url,status:'ok',discovered:candidates.length,terms:rule.terms,publicAllowed:true});
 }catch(e){health.push({publisher:rule.publisher,url:rule.url,status:'unavailable',reason:e.message});}}
if(!health.some(h=>h.status==='ok'&&h.discovered>0))throw Error('No public sources returned records; prior data retained');
const candidates=[],seen=new Set();for(let n=0;n<600;n++)for(const q of queues){const c=q[n];if(c&&!seen.has(c.url)){seen.add(c.url);candidates.push(c);}}
console.log('Checking '+candidates.length+' permitted original pages');
for(const c of candidates){try{if(!c.rule.hosts.includes(new URL(c.url).hostname))throw Error('Article host does not match publisher');if(!c.rule.region)await new Promise(r=>setTimeout(r,c.rule.parser?750:10000));const html=await page(c.url);let title,raw,excerpt,author,locator;
 if(c.rule.region){title=clean(html.match(/<h2[^>]*id=["']Titleh2["'][^>]*>([\s\S]*?)<\/h2>/i)?.[1]||'');const dateText=clean(html.match(/<div[^>]*id=["']PrDateTime["'][^>]*>([\s\S]*?)<\/div>/i)?.[1]||'');raw=pibTimestamp(dateText);locator='Visible PIB Posted On timestamp (IST)';author=clean(html.match(/<div[^>]*id=["']MinistryName["'][^>]*>([\s\S]*?)<\/div>/i)?.[1]||'Press Information Bureau');const after=html.slice(html.indexOf('id="PrDateTime"'));excerpt=[...after.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)].map(m=>clean(m[1])).find(t=>t.length>50)||'';}
 else if(c.rule.parser){({title,raw,excerpt,author,locator}=publisherPage(html,c));}
 else{title=meta(html,'og:title');raw=meta(html,'article:published_time');locator='meta article:published_time';author=c.author;excerpt=meta(html,'og:description');if(!/creativecommons\.org\/licenses\/by\/3\.0/i.test(html))throw Error('Page licence not established');}
 if(!title||!raw||!dated(raw)||/[\u0900-\u0dff]/.test(title))throw Error('Missing English title or timestamp');
 if(Date.parse(raw)>Date.now()||Date.now()-Date.parse(raw)>30*86400000){hold('outside_time_window');continue;}
 excerpt=excerpt.split(/\s+/).slice(0,120).join(' ');const place=locateIndia(title,excerpt,geo,c.rule.parser?publisherState(c.url):'');
 const id=createHash('sha256').update(c.url).digest('hex').slice(0,16),checkedAt=new Date().toISOString();const a={id,url:c.url,title,excerpt,author,publisher:c.rule.publisher,sourceKind:c.rule.kind,category:categoryOf(title),sourceScope:'india',language:'en',publishedAt:new Date(raw).toISOString(),timestampRaw:raw,locations:place.locations,mentions:place.mentions,publicAllowed:true,permissionId:c.rule.id,permissionUrl:c.rule.permissionUrl,permissionCheckedAt:c.rule.permissionCheckedAt,licenseUrl:c.rule.licenseUrl,license:c.rule.license,sourceTerms:c.rule.terms,adaptationNotice:c.rule.headlineOnly?'Publisher headline, unchanged. Open the original article for the full account. Personal, non-commercial reading.':'Headline and shortened source excerpt. AI interpretation is separately labelled; no publisher endorsement implied.',firstSeenAt:accepted.get(id)?.firstSeenAt||checkedAt,provenance:{pageFetched:true,headlineMatched:true,timestampLocator:locator,checkedAt,mode:'Original publisher page; public-reuse permission recorded'}};
 if(eligible(a)&&isPublicSource(a)&&indiaRelevant(a))accepted.set(id,a);else hold('validation_failed');
 }catch(e){hold(e.message);}}
const result={schemaVersion:2,generatedAt:new Date().toISOString(),language:'en',mode:'Public permitted sources',coverageNote:'This non-commercial collection combines publisher headlines and attributed open-reuse sources. Coverage varies by place; official releases are the issuing body’s account, not independent confirmation.',sourceRegistry:publicSources,feeds:health,validation:{discovered:candidates.length,held},articles:[...accepted.values()].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt))};
if(!result.articles.length)throw Error('No eligible public articles; prior data retained');await writeFile(new URL('data/news.pending.json',root),JSON.stringify(result));await rename(new URL('data/news.pending.json',root),new URL('data/news.json',root));console.log(JSON.stringify({articles:result.articles.length,held}));
