// Discovery endpoints advertised by publisher pages; availability and reuse rights are separate.
// This expanded registry is for the local preview. Public redistribution is not approved by an RSS URL.
export const feeds=[];
const add=(publisher,url,state='',directory='',terms='Reuse rights not established')=>feeds.push({publisher,url,state,country:'India',language:'en',directory,terms,publicAllowed:false});
for(const path of ['feed','telangana/feed','andhra-pradesh/feed','hyderabad/feed','india/feed','business/feed','education/feed','entertainment/feed','sports/feed'])add('Telangana Today','https://telanganatoday.com/'+path,path.startsWith('telangana')||path.startsWith('hyderabad')?'Telangana':path.startsWith('andhra')?'Andhra Pradesh':'','https://telanganatoday.com/');
for(const path of ['news/telangana','news/hyderabad','news/andhra-pradesh','news/india','business','education','entertainment'])add('Siasat','https://www.siasat.com/'+path+'/feed/',path.includes('telangana')||path.includes('hyderabad')?'Telangana':path.includes('andhra')?'Andhra Pradesh':'','https://www.siasat.com/');
for(const path of ['news/national','news/states','news/cities','news/national/telangana','news/national/andhra-pradesh','news/national/tamil-nadu','business','sport','entertainment','sci-tech/science','news/national/karnataka','news/national/kerala'])add('The Hindu','https://www.thehindu.com/'+path+'/feeder/default.rss',path.endsWith('/telangana')?'Telangana':path.endsWith('/andhra-pradesh')?'Andhra Pradesh':path.endsWith('/tamil-nadu')?'Tamil Nadu':path.endsWith('/karnataka')?'Karnataka':path.endsWith('/kerala')?'Kerala':'','https://www.thehindu.com/rssfeeds/');
for(const [path,state] of [['india',''],['cities/hyderabad','Telangana'],['cities/chennai','Tamil Nadu'],['cities/bangalore','Karnataka'],['cities/mumbai','Maharashtra'],['cities/delhi','Delhi'],['cities/kolkata','West Bengal'],['cities/lucknow','Uttar Pradesh'],['cities/ahmedabad','Gujarat'],['cities/chandigarh','Chandigarh'],['cities/jaipur','Rajasthan'],['cities/bhopal','Madhya Pradesh'],['north-east-india/assam','Assam'],['business',''],['education',''],['sports',''],['entertainment',''],['health-wellness',''],['governance','']])add('Indian Express','https://indianexpress.com/section/'+path+'/feed/',state,'https://indianexpress.com/rss-2/','Personal, non-commercial RSS use only; public reuse requires permission');
for(const suffix of ['india-news','cities-news','south'])add('NDTV.com','https://feeds.feedburner.com/ndtvnews-'+suffix,'','https://www.ndtv.com/rss','Personal, non-commercial RSS use only');
add('Deccan Chronicle','https://www.deccanchronicle.com/google_feeds.xml','','https://www.deccanchronicle.com/');
add('Scroll.in','https://feeds.feedburner.com/ScrollinArticles.rss','','https://scroll.in/');
