const permissionCheckedAt='2026-09-14';
const pib={publisher:'Press Information Bureau',kind:'Official government release',permissionUrl:'https://www.pib.gov.in/content/3604_2_CopyrightPolicy.aspx?lang=1&reg=3',licenseUrl:'https://www.pib.gov.in/content/3604_2_CopyrightPolicy.aspx?lang=1&reg=3',license:'PIB reproduction permission',terms:'Free reproduction with accurate context and prominent source attribution; excludes third-party material',hosts:['www.pib.gov.in','pib.gov.in'],publicAllowed:true,permissionCheckedAt};
export const publicSources=[...[[3,'National'],[5,'Hyderabad'],[6,'Chennai'],[45,'Vijayawada']].map(([region,label])=>({...pib,id:'pib-'+region,label,url:`https://www.pib.gov.in/allRel.aspx?reg=${region}&lang=1`,rss:`https://www.pib.gov.in/RssMain.aspx?ModId=6&lang=1&reg=${region}`,region})),{id:'global-voices-india',publisher:'Global Voices',kind:'Independent reporting',url:'https://globalvoices.org/-/world/south-asia/india/feed/',hosts:['globalvoices.org'],publicAllowed:true,permissionCheckedAt,permissionUrl:'https://globalvoices.org/about/global-voices-attribution-policy/',licenseUrl:'https://creativecommons.org/licenses/by/3.0/',license:'CC BY 3.0',terms:'Attribution to publisher and author, original link, licence link and indication of changes; third-party media excluded'}];

const ndtv={publisher:'NDTV.com',kind:'Publisher RSS headline',hosts:['www.ndtv.com','ndtv.com'],feedHosts:['feeds.feedburner.com'],publicAllowed:true,permissionCheckedAt:'2026-09-21',permissionUrl:'https://www.ndtv.com/rss',licenseUrl:'https://www.ndtv.com/rss',license:'Personal, non-commercial RSS use with attribution',terms:'Personal, non-commercial headline reader; NDTV.com attribution and direct original links. No full article or image republication.',headlineOnly:true,parser:'publisher'};
for(const suffix of ['india-news','cities-news','south'])publicSources.push({...ndtv,id:'ndtv-'+suffix,label:suffix,url:'https://feeds.feedburner.com/ndtvnews-'+suffix});
publicSources.push({id:'factly',publisher:'Factly',kind:'Fact-checking and public-policy reporting',url:'https://factly.in/feed/',hosts:['factly.in'],publicAllowed:true,permissionCheckedAt:'2026-09-21',permissionUrl:'https://factly.in/',licenseUrl:'https://creativecommons.org/licenses/by/4.0/',license:'CC BY 4.0 (written content only)',terms:'Attribute Factly and the author, link the original and licence, indicate shortening. Excludes videos and third-party media.',parser:'publisher',requiredLicense:'creativecommons.org/licenses/by/4.0'});

publicSources.push({id:'mongabay-india',publisher:'Mongabay India',kind:'Environment and conservation reporting',url:'https://india.mongabay.com/feed/',hosts:['india.mongabay.com'],publicAllowed:true,permissionCheckedAt:'2026-09-22',permissionUrl:'https://india.mongabay.com/about/',licenseUrl:'https://creativecommons.org/licenses/by-nd/4.0/',license:'CC BY-ND 4.0',terms:'Original headline with author and publisher attribution, licence and direct original link. Article bodies and images are not republished or adapted.',headlineOnly:true,preferFeedAuthor:true,parser:'publisher'});
publicSources.push({id:'india-water-portal',publisher:'India Water Portal',kind:'Water and environment research and reporting',url:'https://www.indiawaterportal.org/',hosts:['www.indiawaterportal.org'],publicAllowed:true,permissionCheckedAt:'2026-09-22',permissionUrl:'https://www.indiawaterportal.org/terms-of-use',licenseUrl:'https://creativecommons.org/licenses/by-nc-sa/2.5/in/',license:'CC BY-NC-SA 2.5 IN',terms:'Non-commercial use with author/publisher attribution and original/ licence links; adapted extracts remain under CC BY-NC-SA 2.5 IN. No third-party images.',requiredLicense:'CC BY-NC-SA 2.5 IN',discovery:'links',parser:'publisher'});

export function isPublicSource(s){const rule=publicSources.find(r=>r.id===s?.permissionId);try{return !!rule&&s.publicAllowed===true&&s.publisher===rule.publisher&&new URL(s.url).protocol==='https:'&&rule.hosts.includes(new URL(s.url).hostname)&&s.permissionUrl===rule.permissionUrl&&s.licenseUrl===rule.licenseUrl&&!!s.author;}catch{return false;}}
